/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes/route'
import { Route as IndexImport } from './routes/index'
import { Route as NotesIndexImport } from './routes/notes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as NotesNoteIdIndexImport } from './routes/notes/$noteId/index'

// Create/Update Routes

const NotesRouteRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotesIndexRoute = NotesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRouteRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const NotesNoteIdIndexRoute = NotesNoteIdIndexImport.update({
  id: '/$noteId/',
  path: '/$noteId/',
  getParentRoute: () => NotesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexImport
      parentRoute: typeof NotesRouteImport
    }
    '/notes/$noteId/': {
      id: '/notes/$noteId/'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdIndexImport
      parentRoute: typeof NotesRouteImport
    }
  }
}

// Create and export the route tree

interface NotesRouteRouteChildren {
  NotesIndexRoute: typeof NotesIndexRoute
  NotesNoteIdIndexRoute: typeof NotesNoteIdIndexRoute
}

const NotesRouteRouteChildren: NotesRouteRouteChildren = {
  NotesIndexRoute: NotesIndexRoute,
  NotesNoteIdIndexRoute: NotesNoteIdIndexRoute,
}

const NotesRouteRouteWithChildren = NotesRouteRoute._addFileChildren(
  NotesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/notes/$noteId': typeof NotesNoteIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/notes': typeof NotesIndexRoute
  '/notes/$noteId': typeof NotesNoteIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/notes/$noteId/': typeof NotesNoteIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes' | '/auth' | '/notes/' | '/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/notes' | '/notes/$noteId'
  id: '__root__' | '/' | '/notes' | '/auth/' | '/notes/' | '/notes/$noteId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRouteRoute: typeof NotesRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRouteRoute: NotesRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notes": {
      "filePath": "notes/route.tsx",
      "children": [
        "/notes/",
        "/notes/$noteId/"
      ]
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/notes/": {
      "filePath": "notes/index.tsx",
      "parent": "/notes"
    },
    "/notes/$noteId/": {
      "filePath": "notes/$noteId/index.tsx",
      "parent": "/notes"
    }
  }
}
ROUTE_MANIFEST_END */
